---
- name: ensure dependencies available through apt are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - nginx
    - openssl
    - php5-curl
    - php5-fpm
    - php5-gd
    - php5-json
    - php5-mcrypt
    - php5-mysql

- name: ensure that mcrypt module is enabled
  command: php5enmod mcrypt creates=/etc/php5/fpm/conf.d/20-mcrypt.ini
  notify:
    - restart php5-fpm

- name: ensure /var/cache/ansible directory exists
  file:
    path: /var/cache/ansible
    owner: root
    group: root
    mode: 0755
    state: directory

- name: download the ttrss install package
  get_url:
    url: "{{ ttrss_download_url }}"
    dest: /var/cache/ansible/ttrss.tar.gz

- name: create self-signed key/certificate pair if required
  shell: >
          openssl req -newkey rsa:2048 -x509 -nodes
          -days 365 -subj "/CN={{ ttrss_hostname }}"
          -out {{ ttrss_ssl_cert_file }}
          -keyout {{ ttrss_ssl_key_file }} &&
          update-ca-certificates
          creates={{ ttrss_ssl_cert_file }}

- name: ensure that ttrss group exists
  group:
    name: ttrss
    state: present

- name: ensure that ttrss user exits
  user:
    name: ttrss
    group: ttrss
    home: /srv/ttrss
    createhome: yes
    shell: /bin/bash
    state: present

- name: unarchive ttrss to /srv/ttrss
  command: tar --strip-components 1 -xvzf /var/cache/ansible/ttrss.tar.gz
           chdir=/srv/ttrss
           creates=/srv/ttrss/index.php

- name: ensure /srv/ttrss is owned by ttrss user
  file:
    path: /srv/ttrss
    owner: ttrss
    group: ttrss
    recurse: yes

- name: ensure ttrss database is present
  mysql_db:
    name: ttrss
    state: present

- name: ensure ttrss database user is present
  mysql_user:
    name: ttrss
    host: "{{ item }}"
    password: "{{ ttrss_ttrss_mysql_password }}"
    priv: ttrss.*:ALL
    state: present
  with_items:
    - "%"
    - localhost

- name: initialize ttrss database
  sudo_user: ttrss
  shell: mysql -u ttrss -p"{{ ttrss_ttrss_mysql_password }}" ttrss < /srv/ttrss/schema/ttrss_schema_mysql.sql
         && touch /srv/ttrss/.mysql_schema
         creates=/srv/ttrss/.mysql_schema

- name: copy .my.cnf file with ttrss password credentials
  template:
    src: srv/ttrss/.my.cnf
    dest: /srv/ttrss/.my.cnf
    owner: ttrss
    group: ttrss
    mode: 0600

- name: update /srv/ttrss/config.php from template
  template:
    src: srv/ttrss/config.php
    dest: /srv/ttrss/config.php
    owner: ttrss
    group: ttrss
    mode: 0600

- name: update /etc/php5/fpm/pool.d/ttrss.conf from template
  template:
    src: etc/php5/fpm/pool.d/ttrss.conf
    dest: /etc/php5/fpm/pool.d/ttrss.conf 
    owner: root
    group: root
    mode: 0644
  notify:
    - restart php5-fpm

- name: update /etc/nginx/sites-available/ttrss from template
  template:
    src: etc/nginx/sites-available/ttrss
    dest: /etc/nginx/sites-available/ttrss
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: ensure /etc/nginx/sites-enabled/ttrss exists and links to ../sites-available/ttrss
  file:
    path: /etc/nginx/sites-enabled/ttrss
    src: ../sites-available/ttrss
    force: yes
    state: link
  notify:
    - restart nginx

- name: ensure that there is not a hostname collision with the nginx default host
  lineinfile:
    dest: /etc/nginx/sites-available/default
    regexp: '^(\s+)(server_name {{ ttrss_hostname }};.*)$'
    backrefs: yes
    line: '\1#\2'
    state: present
  notify:
    - restart nginx

- name: ensure ttrss services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - nginx
    - php5-fpm

